hams/lib/hams_web/router.ex
defmodule HamsWeb.Router do
  use HamsWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug HamsWeb.Plugs.FetchSession
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", HamsWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/users", UserController
    resources "/tours", TourController
    resources "/schedule_tours", ScheduleTourController
    resources "/sessions", SessionController, only: [:create, :delete], singleton: true
  end

  # Other scopes may use custom stacks.
  # scope "/api", HamsWeb do
  #   pipe_through :api
  # end
end

hams/lib/hams_web/views/layout_view.ex
defmodule HamsWeb.LayoutView do
  use HamsWeb, :view
end

hams/lib/hams_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Husky Ambassadors Management System </title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg bg-red text-white">
        <!-- image from https://twitter.com/Northeastern?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor -->
        <a class="navbar-brand" href="/"><img class="northeasternn" src="<%= Routes.static_path(@conn, "/images/northeasternn.jpg") %>"/></a>
        <ul class="navbar-nav">
          <li class="nav-item ">
            <a class="nav-link bg-red text-white" href="/">Home</a>
          </li>
          <%= if @current_user do %>
            <li class="nav-item">
              <%= link "Tours", to: Routes.tour_path(@conn, :index), class: "nav-link text-white" %>
            </li>
            <li class="nav-item">
              <%= link "Profile", to: Routes.user_path(@conn, :show, @current_user.id), class: "nav-link text-white" %>
            </li>
            <li class="nav-item">
              <%= link("Logout", to: Routes.session_path(@conn, :delete), method: :delete, class: "nav-link text-white") %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= form_for @conn, Routes.session_path(@conn, :create), [class: "form-inline"], fn f -> %>
                <%= text_input(f, :email, class: "form-control", placeholder: "email") %>
                <%= password_input(f, :password, class: "form-control", placeholder: "password") %>
                <%= submit "Login", class: "btn btn-secondary" %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </nav>

      <div class="row">
        <div class="col-12">
          <%= render @view_module, @view_template, assigns %>
        </div>
      </div>
    </div>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>