hams/lib/hams_web/router.ex
defmodule HamsWeb.Router do
  use HamsWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug HamsWeb.Plugs.FetchSession
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", HamsWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/users", UserController
    resources "/tours", TourController
    resources "/schedule_tours", ScheduleTourController
    resources "/sessions", SessionController, only: [:create, :delete], singleton: true
  end

  # Other scopes may use custom stacks.
  # scope "/api", HamsWeb do
  #   pipe_through :api
  # end
end

hams/lib/hams/tours/tour.ex
defmodule Hams.Tours.Tour do
  use Ecto.Schema
  import Ecto.Changeset

  schema "tours" do
    field :guides_needed, :integer
    field :type, :string
    field :when, :naive_datetime

    timestamps()
  end

  @doc false
  def changeset(tour, attrs) do
    tour
    |> cast(attrs, [:when, :type, :guides_needed])
    |> validate_required([:when, :type, :guides_needed])
  end
end

hams/lib/hams/tours/tours.ex
defmodule Hams.Tours do
  @moduledoc """
  The Tours context.
  """

  import Ecto.Query, warn: false
  alias Hams.Repo

  alias Hams.Tours.Tour
  alias Hams.Schedules
  alias Hams.Schedules.ScheduleTour

  @doc """
  Returns the list of tours.

  ## Examples

      iex> list_tours()
      [%Tour{}, ...]

  """
  def list_tours do
    Repo.all(Tour)
  end

  @doc """
  Gets a single tour.

  Raises `Ecto.NoResultsError` if the Tour does not exist.

  ## Examples

      iex> get_tour!(123)
      %Tour{}

      iex> get_tour!(456)
      ** (Ecto.NoResultsError)

  """
  def get_tour!(id), do: Repo.get!(Tour, id)

  def get_user_tours!(userId) do
    query = from st in ScheduleTour,
              join: t in Tour, where: st.tour_id == t.id and st.user_id == ^userId,
              select: {t.when, t.type}
    Repo.all(query)
  end

  @doc """
  Creates a tour.

  ## Examples

      iex> create_tour(%{field: value})
      {:ok, %Tour{}}

      iex> create_tour(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_tour(attrs \\ %{}) do
    %Tour{}
    |> Tour.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a tour.

  ## Examples

      iex> update_tour(tour, %{field: new_value})
      {:ok, %Tour{}}

      iex> update_tour(tour, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_tour(%Tour{} = tour, attrs) do
    tour
    |> Tour.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a Tour.

  ## Examples

      iex> delete_tour(tour)
      {:ok, %Tour{}}

      iex> delete_tour(tour)
      {:error, %Ecto.Changeset{}}

  """
  def delete_tour(%Tour{} = tour) do
    Repo.delete(tour)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking tour changes.

  ## Examples

      iex> change_tour(tour)
      %Ecto.Changeset{source: %Tour{}}

  """
  def change_tour(%Tour{} = tour) do
    Tour.changeset(tour, %{})
  end
end

hams/lib/hams_web/controllers/tour_controller.ex
defmodule HamsWeb.TourController do
  use HamsWeb, :controller

  alias Hams.Tours
  alias Hams.Tours.Tour
  alias Hams.Users
  alias Hams.Users.User

  def index(conn, _params) do
    tours = Tours.list_tours()
    render(conn, "index.html", tours: tours)
  end

  def new(conn, _params) do
    current_user = Users.get_user(get_session(conn, :user_id) || -1)

    if current_user && current_user.admin do
      changeset = Tours.change_tour(%Tour{})
      render(conn, "new.html", changeset: changeset)
    else
      redirect(conn, to: Routes.page_path(conn, :index))
    end
  end

  def create(conn, %{"tour" => tour_params}) do
    case Tours.create_tour(tour_params) do
      {:ok, tour} ->
        conn
        |> put_flash(:info, "Tour created successfully.")
        |> redirect(to: Routes.tour_path(conn, :show, tour))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    current_user = Users.get_user(get_session(conn, :user_id) || -1)

    if current_user.admin do
      tour = Tours.get_tour!(id)
      render(conn, "show.html", tour: tour)
    else
      redirect(conn, to: Routes.page_path(conn, :index))
    end

  end

  def edit(conn, %{"id" => id}) do
    current_user = Users.get_user(get_session(conn, :user_id) || -1)

    if current_user.admin do
      tour = Tours.get_tour!(id)
      changeset = Tours.change_tour(tour)
      render(conn, "edit.html", tour: tour, changeset: changeset)
    else
      redirect(conn, to: Routes.page_path(conn, :index))
    end
  end

  def edit(conn, %{"id" => id, "user" => user}) do
    tour = Tours.get_tour!(id)
    current_user = Users.get_user(get_session(conn, :user_id) || -1)

    # case Tours.update_tour(tour, tour_params) do
    #   {:ok, tour} ->
    #     conn
    #     |> put_flash(:info, "Tour joined successfully.")
    #
    #   {:error, %Ecto.Changeset{} = changeset} ->
    #     conn
    #     |> put_flash(:error, "An error occurred, please try again.")
    # end

  end

  def update(conn, %{"id" => id, "tour" => tour_params}) do
    tour = Tours.get_tour!(id)

    case Tours.update_tour(tour, tour_params) do
      {:ok, tour} ->
        conn
        |> put_flash(:info, "Tour updated successfully.")

      {:error, %Ecto.Changeset{} = changeset} ->
        conn
        |> put_flash(:info, "An error occurred, please try again.")
    end
  end

  def delete(conn, %{"id" => id}) do
    tour = Tours.get_tour!(id)
    {:ok, _tour} = Tours.delete_tour(tour)

    conn
    |> put_flash(:info, "Tour deleted successfully.")
    |> redirect(to: Routes.tour_path(conn, :index))
  end
end

hams/lib/hams_web/views/tour_view.ex
defmodule HamsWeb.TourView do
  use HamsWeb, :view
end

hams/lib/hams_web/templates/tour/edit.html.eex
<div class="row">
  <div class="col-6">
    <h2 class="d-inline">Edit Tour</h2>
    <%= render "form.html", Map.put(assigns, :action, Routes.tour_path(@conn, :update, @tour)) %>
  </div>
</div>

hams/lib/hams_web/templates/tour/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>


  <table class="table">
    <tr><td><%= label f, :when %></td><td><%= datetime_select f, :when %></td><td><%= error_tag f, :when %></td></tr>
    <tr><td><%= label f, :type %></td><td><%= select f, :type, ["Admitted": "Admitted", "Prospective": "Prospective"] %></td><td><%= error_tag f, :type %></td></tr>
    <tr><td><%= label f, :guides_needed %></td><td><%= text_input f, :guides_needed %></td><td><%= error_tag f, :guides_needed %></td></tr>
  </table>

  <div>
    <%= submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

hams/lib/hams_web/templates/tour/index.html.eex
<div class="row">
  <div class="col-12">
    <h2 class="d-inline">Tours</h2>
    <table class="table">
      <thead>
        <tr>
          <th>When</th>
          <th>Type</th>
          <th>Guides Needed</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
    <%= for tour <- @tours do %>
        <tr>
          <td class="align-middle"><%= tour.when %></td>
          <td class="align-middle"><%= tour.type %></td>
          <td class="align-middle"><%= tour.guides_needed %></td>
          <td>
            <%= if tour.guides_needed > 0 do %>
              <%= link "Join", to: Routes.schedule_tour_path(@conn, :create, schedule_tour: %{user_id: @current_user.id, tour_id: tour.id}), method: :create, class: "btn btn-primary" %>
            <% else %>
              <%= link "Join", to: Routes.page_path(@conn, :index), class: "btn btn-secondary disabled" %>
            <% end %>
          </td>
          <td>
            <%= if @current_user && @current_user.admin do %>
              <%= link "Edit", to: Routes.tour_path(@conn, :edit, tour), class: "btn btn-secondary" %>
            <% end %>
          </td>
        </tr>
    <% end %>
      </tbody>
    </table>
  </div>
</div>

hams/lib/hams_web/templates/tour/new.html.eex
<div class="row">
  <div class="col-6">
    <h2 class="d-inline">Add Tour</h2>
    <%= render "form.html", Map.put(assigns, :action, Routes.tour_path(@conn, :create)) %>
  </div>
</div>

hams/lib/hams_web/templates/tour/show.html.eex
<div class="row">
  <div class="col-6">
    <h2 class="d-inline">Tour Info</h2>
    <%= link "Edit", to: Routes.tour_path(@conn, :edit, @tour), class: "btn btn-secondary float-right" %>
    <table class="table">
      <tr><td>When</td><td><%= @tour.when %></td></tr>
      <tr><td>Type</td><td><%= @tour.type %></td></tr>
      <tr><td>Guides Needed</td><td><%= @tour.guides_needed %></td></tr>
    </table>
  </div>
  <div class="col-6">
  </div>

<%= if @current_user.admin do %>
<span><%= link "Delete", to: Routes.tour_path(@conn, :delete, @tour), method: :delete, data: [confirm: "Delete?"], class: "btn btn-danger" %></span>
<% end %>